# This notebook demonstrates how to use TensorFlow and Keras for classification tasks

## Step 1: Prepare

#### 1. Create Virtual Environment `(.venv)` and activate it by using this command:
#### ```.venv\Scripts\activate```
#### 2. Change the Notebook Kernel to Use .venv:
#### - In VS Code, click on the kernel name in the top-right of the notebook (it shows "base (Python 3.10.9)").
#### - Select "Change Kernel" > "Python Environments".
#### - Choose the .venv environment (it should appear as something like "Python 3.10.x ('.venv': venv)").
#### - Restart the kernel if prompted.
#### 3. Install, update libs:
#### - To install libs, use `python -m pip install <lib_name_1 lib_name_2 ...>`
#### - To update pip, use `python -m pip install --upgrade pip`

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# numpy is used for numerical operations
# pandas is used to handle data in tabular form
# sklearn is used for machine learning tasks
# using train_test_split to split the dataset into training and testing sets
# using accuracy_score to evaluate the model's performance
# using the Iris dataset for classification tasks

In [3]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier

# using Keras to build neural network models
# using Sequential model to stack layers linearly
# using Dense layers for fully connected neural network layers
# using GridSearchCV for hyperparameter tuning
# using KerasClassifier to wrap Keras models for use in scikit-learn

In [4]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
Y = iris.target

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# Split the dataset into training and testing sets
# 20% of the data is used for testing, and 80% for training
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

## Step 2: Find the best activation function using grid search:
#### (This step can be ignored, you can choose an activation function you want)

In [7]:
# Define a function to create the Keras model
def create_model(activation='relu'):
    model = Sequential()
    model.add(Dense(8, input_dim=4, activation=activation))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Wrap the model using KerasClassifier
# model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=10, verbose=0)
model = KerasClassifier(model=create_model, epochs=50, batch_size=10, verbose=0)

In [8]:
# Define parameter grid for grid search
param_grid = {
    'model__activation': ['relu', 'tanh', 'sigmoid'],
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3)
grid_search_result = grid_search.fit(X_train, Y_train)

d:\Dev\Python\AI\project\learning_AI\.venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
d:\Dev\Python\AI\project\learning_AI\.venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
d:\Dev\Python\AI\project\learning_AI\.venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init

In [9]:
# # Print the best parameters and accuracy from grid search
# print("Best Parameters: ", grid_search_result.best_params_)
# print("Best Cross-Validation Accuracy: ", grid_search_result.best_score_)

# # Get the best model from grid search
# best_model = grid_search_result.best_estimator_

# # Train the best model on the full training data
# best_model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=0)

# Print the best parameters and accuracy from grid search
print("Best Parameters: ", grid_search_result.best_params_)
print("Best Cross-Validation Accuracy: ", grid_search_result.best_score_)

# Get the best activation from grid search
best_activation = grid_search_result.best_params_['model__activation']

# Create the best model with the optimal activation
best_model = create_model(activation=best_activation)

# Train the best model on the full training data
best_model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=0)

Best Parameters:  {'model__activation': 'tanh'}
Best Cross-Validation Accuracy:  0.9249999999999999


d:\Dev\Python\AI\project\learning_AI\.venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
# Make predictions on the test set
Y_pred = best_model.predict(X_test)
# Y_pred = np.argmax(best_model.predict(X_test), axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step


In [11]:
print("Test Set Predictions: ", Y_pred)

Test Set Predictions:  [[0.07011752 0.6695833  0.26029915]
 [0.91629416 0.07635732 0.0073485 ]
 [0.00935303 0.23673135 0.75391555]
 [0.0582151  0.51661724 0.42516768]
 [0.05764023 0.6043178  0.33804196]
 [0.9047743  0.08516078 0.01006484]
 [0.16398276 0.5498147  0.28620243]
 [0.01850006 0.20330036 0.77819955]
 [0.03651476 0.4476011  0.5158841 ]
 [0.11586465 0.6212017  0.26293364]
 [0.02607187 0.3093057  0.6646224 ]
 [0.89001286 0.10227712 0.00771005]
 [0.92463195 0.06870873 0.00665938]
 [0.88843286 0.10398738 0.00757976]
 [0.92747027 0.06572695 0.00680273]
 [0.06348798 0.5211283  0.41538373]
 [0.01308431 0.23394035 0.7529754 ]
 [0.10583397 0.64769506 0.24647105]
 [0.06705657 0.60263306 0.3303103 ]
 [0.01253689 0.2179595  0.7695036 ]
 [0.88681227 0.10469503 0.00849275]
 [0.03141546 0.36859536 0.5999892 ]
 [0.8987015  0.09109474 0.01020384]
 [0.01409002 0.24848787 0.7374221 ]
 [0.02536867 0.45151144 0.52311987]
 [0.01554853 0.19491775 0.78953373]
 [0.0180076  0.35728344 0.62470895]
 [0.0

In [12]:
print(Y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [13]:
Y_pred = np.argmax(Y_pred, axis=1)
print("Test Set Predictions (argmax): ", Y_pred)

Test Set Predictions (argmax):  [1 0 2 1 1 0 1 2 2 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [20]:
# Print accuracy on the test set
accuracy = accuracy_score(Y_test, Y_pred)
print("Test Set Accuracy: ", accuracy)

# Print weights and biases of each layer
print("\nModel Weights and Biases:")
for i, layer in enumerate(best_model.layers):
    weights, biases = layer.get_weights()
    print(f"Layer {i+1} - {layer.name}")
    print(f"- Weights Shape: {weights.shape}\n{weights}")
    print(f"- Biases Shape: {biases.shape}\n{biases}")

Test Set Accuracy:  0.9666666666666667

Model Weights and Biases:
Layer 1 - dense_20
- Weights Shape: (4, 8)
[[-0.02008527  0.03756171 -0.14580107 -0.36362863  0.7149558  -0.05021526
   0.04648174 -0.15869975]
 [ 0.27207488  0.16891359 -0.41603252 -0.23046765 -0.42147467  0.55137837
  -0.0433121   0.48670235]
 [-0.0452649  -0.4384897   0.17211711  0.7454228   0.61940074 -0.59757084
  -0.1786219   0.03397739]
 [ 0.18808776  0.6221204   0.8538396   0.18630308  0.1808473  -0.02969743
   1.0407312  -1.0672219 ]]
- Biases Shape: (8,)
[-0.49925283 -0.17237742 -0.01164678 -0.21731022  0.13021238  0.13663432
 -0.59217846  0.3873145 ]
Layer 2 - dense_21
- Weights Shape: (8, 3)
[[ 0.21113676  0.03353009  0.3262008 ]
 [ 0.39848146 -0.5917177   0.2725606 ]
 [-0.37084967 -0.54999816  0.8736867 ]
 [-0.04705875  0.6316504   1.0433338 ]
 [ 0.62298423  0.3343676   0.15248832]
 [ 0.47543895 -0.96403337 -0.8986601 ]
 [-0.7165106  -0.17751181  0.60303426]
 [ 0.68752325  0.27857944  0.05490923]]
- Biases S